frame_rate: 0.5

telegram:
  api_id: "set-me"
  api_hash: set-me
  # E.g. t.me/<channel>
  destination_entity: set-me
# Region of interest
# roi:
#   width: 1000
#   height: 1000
#   offset_x: 0
#   offset_y: 0

detection:
  # Add padding to detected objects.
  # In pixels.
  padding: 100
  interval_seconds: 15
  # Delete detection files older than this.
  # Prevents it from growing indefinitely.
  max_detection_file_age_hours: 72

digest:
  min_interval_seconds: 300
